# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.dev                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pguthaus <pguthaus@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/10/07 18:57:53 by pguthaus          #+#    #+#              #
#    Updated: 2019/10/18 18:50:53 by pguthaus         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

include make/config.mk

# Sources sets
include make/srcs.mk

# Compilation
CFLAGS			=			-g -fsanitize=address

# Paths
OUTDIR			=			./objs/dev/

# OBJS
OBJS			=			$(addprefix $(OUTDIR),$(FT_SRCS:.c=.o))

dev: $(DEV_NAME)

re: fclean $(DEV_NAME)

$(DEV_NAME): $(OBJS)
	ar rcs $(DEV_NAME) $(OBJS)

$(OUTDIR)%.o: $(SRCDIR)%.c
	@if [ ! -d $(dir $@) ]; then mkdir -p $(dir $@); fi
	$(CC) $(CFLAGS) -I $(INCDIR) -o $@ -c $<

clean:
	@rm -rf $(OUTDIR)

fclean:
	@rm -rf $(DEV_NAME)
